force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payroll Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Void__c.field-meta.xml
<CustomField>
    <fullName>Void__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Void</description>
    <label>Void</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PaymentContactCalculationSchedulable.cls
public with sharing class PaymentContactCalculationSchedulable implements Schedulable{
    public void execute(SchedulableContext ctx) {
        Date currentDate = Date.today();

        List<Payment__c> lstPayments = [SELECT 
                Id,
                Contact__c
            FROM
                Payment__c
            WHERE
                CALENDAR_MONTH(Payment_Date__c) = :currentDate.month()
                AND CALENDAR_YEAR(Payment_Date__c) = :currentDate.year()
                AND Void__c = False];

        PaymentService.calculateTotalPaymentAmountThisMonth(lstPayments);
    }
}