force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payroll Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    
</CustomField>

force-app/main/default/objects/Payment__c/fields/Void__c.field-meta.xml
<CustomField>
    <fullName>Void__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Void</description>
    <label>Void</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountPaymentsCtl.cls
public with sharing class AccountPaymentsCtl {
    @AuraEnabled
    public static String getAccounts() {
        List<Account> lstAccounts = new List<Account>([SELECT Id, Name FROM Account]);
        AggregateResult[] lstRes = [SELECT COUNT(Id), Account__c FROM Payment__c WHERE Void__c = False GROUP BY Account__c ];

        List<AccountPaymentDto> lstAccountPayments = new List<AccountPaymentDto>();

        for (Account a : lstAccounts) {
            Boolean accountFound = false;
            for (AggregateResult res : lstRes) {
                if (a.Id == res.get('Account__c')) {
                    accountFound = true;
                    AccountPaymentDto apd = new AccountPaymentDto();

                    apd.accountId = a.Id;
                    apd.accountName = a.Name;
                    apd.numberOfPayments = (Integer)res.get('expr0');

                    lstAccountPayments.add(apd);
                }
            }

            if (!accountFound) {
                AccountPaymentDto apd = new AccountPaymentDto();
                apd.accountId = a.Id;
                apd.accountName = a.Name;
                apd.numberOfPayments = 0;

                lstAccountPayments.add(apd);
            }
        }

        return JSON.serialize(lstAccountPayments);
    }

    @AuraEnabled
    public static void voidPayment(String accountId){
        List<Payment__c> lstPayments = [SELECT Id, Void__c FROM Payment__c WHERE Account__c = :accountId];

        for (Payment__c p : lstPayments) {
            p.Void__c = True;
        }

        update lstPayments;

        return;
    }

    public class AccountPaymentDto {
        public String   accountName         { get; set; }
        public String   accountId           { get; set; }
        public Integer  numberOfPayments    { get; set; }
    }
}